export type ArticleSection = {
  title: string;
  paragraphs: string[];
  keyPoints: string[];
  examPrompt: string;
};

export type StudyArticle = {
  key: string;
  title: string;
  deck: string;
  intro: string;
  mentorPriority: string[];
  corrections?: string[];
  sections: ArticleSection[];
  sources: { label: string; url: string }[];
};

export const dsoArticles: StudyArticle[] = [
  {
    key: 'andromeda',
    title: 'Andromeda Galaxy',
    deck: 'Andromeda Galaxy.pptx, slides 2–15 and 17–22',
    intro: 'The mentor deck uses Andromeda to connect spiral morphology, the Local Group, distance measurement, galaxy structure, and multiwavelength imaging. Treat it as both an identification target and the reference example for a nearby barred spiral.',
    mentorPriority: ['M31 = NGC 224', 'Nearest major galaxy to the Milky Way', 'Barred spiral despite its optical SA(s)b appearance', 'Local Group member with satellites M32 and M110', 'Complex double nucleus and central black hole'],
    sections: [
      { title: 'Morphology and visual recognition', paragraphs: ['Andromeda is a large spiral seen at a high inclination. In ordinary visible images it appears as a long oval with a bright central bulge, dark dust lanes, and an extended disk. Wide fields often include the compact elliptical M32 near the disk and the diffuse dwarf elliptical M110 farther away.', 'The deck stresses that infrared observations reveal a central bar whose major axis is rotated relative to the disk. That makes Andromeda a barred spiral even though older visible-light classifications often list SA(s)b.'], keyPoints: ['Large inclined disk rather than a true edge-on disk', 'Bright bulge and layered dust lanes', 'M32 and M110 are high-value context clues', 'Optical and infrared morphology can lead to different classifications'], examPrompt: 'Explain why Andromeda can appear unbarred in visible light yet be classified as a barred spiral.' },
      { title: 'Structure and stellar populations', paragraphs: ['The deck describes two light concentrations in the nucleus. P2 marks the true dynamical center and contains P3, a compact cluster of ultraviolet-bright A stars around the supermassive black hole M31*. P1 is offset from the true center.', 'Andromeda has roughly 460 associated globular clusters in the mentor material. Their ages span a wider range than the Milky Way globular-cluster population. Mayall II is exceptionally luminous and massive and may be more complex than an ordinary globular cluster.'], keyPoints: ['P1 is offset; P2 is the true center', 'P3 contains UV-bright stars around M31*', 'Mayall II is an unusually massive Local Group cluster', 'Andromeda has many dwarf satellites'], examPrompt: 'Identify P1, P2, P3, and M31* in a labeled nucleus diagram.' },
      { title: 'Local Group and historical importance', paragraphs: ['Andromeda and the Milky Way dominate the Local Group, whose membership is mostly dwarf galaxies. The group belongs to the larger local cosmic structure associated with the Virgo and Laniakea superclusters.', 'Al-Sufi recorded the object as a small cloud in 964. Edwin Hubble later used Cepheid variables in Andromeda to establish that it lies outside the Milky Way. The deck also highlights SN 1885A, the first supernova observed beyond the Milky Way.'], keyPoints: ['Hubble used Cepheids to settle the island-universe debate', 'M31 is blueshifted', 'SN 1885A is also S Andromedae', 'The deck gives about a 50% Milky Way collision probability within 10 billion years'], examPrompt: 'Connect Cepheid variables in M31 to the historical proof that other galaxies exist.' },
      { title: 'Reading the wavelengths', paragraphs: ['Far-infrared and radio images emphasize cold dust and gas. Ultraviolet and H-alpha views emphasize recent star formation. Visible mosaics show the stellar disk and dust lanes, while high-resolution Hubble images resolve individual stars, clusters, and the nucleus.', 'The PHAT and PHAST surveys built a huge multi-band mosaic from hundreds of Hubble pointings. The point of the slide is not only the pixel count: resolved stellar populations let astronomers reconstruct merger and star-formation history.'], keyPoints: ['Far-IR traces cool dust', 'H-alpha traces ionized gas around young stars', 'UV favors hot young stars', 'Resolved populations preserve the history of the disk'], examPrompt: 'Given optical, UV, and far-infrared images of M31, state what physical component each band emphasizes.' },
    ],
    sources: [{ label: 'NASA Hubble Messier 31', url: 'https://science.nasa.gov/mission/hubble/science/explore-the-night-sky/hubble-messier-catalog/messier-31/' }],
  },
  {
    key: 'antennae',
    title: 'Antennae Galaxies',
    deck: 'Antennae Galaxies.pptx, slides 2–17',
    intro: 'The Antennae are the mentor deck’s main case study for a major merger. The important chain is gravitational interaction, tidal tails, gas compression, starburst, super star clusters, and eventual coalescence.',
    mentorPriority: ['NGC 4038 + NGC 4039 = Arp 244', 'Interacting former spirals in Corvus', 'Long tidal tails create the antennae', 'Dusty overlap region and intense star formation', 'Future merger remnant is expected to resemble an elliptical galaxy'],
    sections: [
      { title: 'How a major merger changes galaxies', paragraphs: ['The two galaxies began interacting hundreds of millions of years ago. Their stars rarely collide directly because galaxies are mostly empty space, but the changing gravitational field strongly alters stellar orbits and pulls out enormous tidal tails.', 'Gas clouds do collide and compress. That compression explains why the overlap region and distorted arms contain brilliant H II regions and young clusters. The deck’s timeline places the first passage hundreds of millions of years in the past and core coalescence roughly 400 million years in the future.'], keyPoints: ['Tidal forces move stars without many star-star collisions', 'Gas compression drives the starburst', 'Tails record the orbital history', 'The two visible cores are still distinct'], examPrompt: 'Why can a galaxy collision trigger star formation even though individual stars usually miss one another?' },
      { title: 'Recognition and spatial anatomy', paragraphs: ['Wide-field images reveal two long curved tails. Hubble close-ups may crop those tails out, so use the two orange-yellow nuclei, dark dust filaments, blue clusters, and the dusty band between the cores as recognition clues.', 'The deck calls the band between the galaxies the overlap region. It is especially rich in dense gas and embedded star formation.'], keyPoints: ['Two nuclei plus chaotic central dust', 'Long tails are easiest in wide fields', 'Blue knots are young clusters', 'Pink H-alpha regions are ionized star-forming gas'], examPrompt: 'Identify the nuclei, overlap region, and tidal tails on both a wide-field and a cropped Hubble image.' },
      { title: 'Super star clusters and feedback', paragraphs: ['The mentor slides emphasize more than a thousand young super star clusters. Most young clusters will disperse, but the most massive may survive and evolve into objects resembling globular clusters.', 'X-ray images show compact neutron-star and black-hole binaries along with multimillion-degree gas. Supernovae and stellar winds enrich and heat this gas, producing loops that extend away from the merger.'], keyPoints: ['Cluster formation is a direct merger consequence', 'X-ray points often mark compact remnants in binaries', 'Diffuse X-rays trace hot gas', 'ALMA carbon monoxide maps dense cold molecular clouds'], examPrompt: 'Compare what ALMA, Hubble, Spitzer, and Chandra reveal in the Antennae.' },
    ],
    sources: [{ label: 'NASA Hubble Antennae', url: 'https://science.nasa.gov/asset/hubble/the-antennae-galaxiesngc-4038-4039/' }],
  },
  {
    key: 'arp-143',
    title: 'Arp 143',
    deck: 'Arp 143.pptx, slides 2–10',
    intro: 'Arp 143 contrasts a gas-poor lenticular galaxy, NGC 2444, with the gas-rich distorted ring galaxy NGC 2445. The collision explains the bridge, triangular star-forming pattern, and inward age sequence.',
    mentorPriority: ['NGC 2444 on the left and NGC 2445 on the right', 'Located in Lynx and associated with LGG 148', 'NGC 2444 is old and gas-poor', 'NGC 2445 contains the ring and new stars', 'Youngest stars lie closest to NGC 2445’s center'],
    corrections: ['The deck uses about 135 ± 35 million light-years. NASA’s 2022 image page lists about 191 million light-years. Use the mentor value for mentor-written questions, but recognize that published distance estimates differ.'],
    sections: [
      { title: 'The unequal pair', paragraphs: ['NGC 2444 is a peculiar lenticular galaxy dominated by old stars. It had already lost most of its star-forming gas before the present encounter. NGC 2445 is gas-rich and strongly distorted.', 'The larger NGC 2444 pulls gas from NGC 2445. A bridge of young blue stars and gas reaches between them, making the interaction visible.'], keyPoints: ['Left component is the gas-poor lenticular', 'Right component is the active ring galaxy', 'A stellar and gaseous bridge connects them', 'The collision is a gravitational tug-of-war'], examPrompt: 'Use stellar color and gas content to distinguish NGC 2444 from NGC 2445.' },
      { title: 'A moving wave of star formation', paragraphs: ['A previous head-on encounter produced a ring-shaped wave in NGC 2445. Later interaction distorted that ring into the present triangular appearance. The streamers contain stars roughly 50 to 100 million years old, ring knots are about 2 to 8 million years old, and stars close to the center can be only 1 to 2 million years old.', 'That age pattern shows star formation progressing inward in the current geometry. Carbon monoxide emission shows that NGC 2445 still has molecular gas available for future star formation.'], keyPoints: ['Do not describe the system as one static ring', 'Stellar ages change with position', 'CO emission is evidence for molecular gas', 'H II regions outline recent massive-star formation'], examPrompt: 'Infer the direction of the star-formation wave from the ages of streamers, ring knots, and central stars.' },
      { title: 'Radio and large-scale evidence', paragraphs: ['Radio emission from NGC 2445 is asymmetric and includes the nucleus, star-forming regions, and a ridge toward NGC 2444. The deck also discusses a large hydrogen shell or tail far from the pair.', 'These features show that an interaction redistributes gas on scales far larger than the bright optical bodies.'], keyPoints: ['Radio maps reveal gas and magnetic-field structure', 'A distant hydrogen feature may be a superbubble or tidal tail', 'The system belongs to the small LGG 148 group'], examPrompt: 'Explain why neutral-hydrogen and radio-continuum maps are useful even when the optical collision is already visible.' },
    ],
    sources: [{ label: 'NASA Hubble Arp 143', url: 'https://science.nasa.gov/asset/hubble/arp-143/' }],
  },
  {
    key: 'arp-147',
    title: 'Arp 147',
    deck: 'Arp 147.pptx, slides 2–14',
    intro: 'Arp 147 is the “10” system: an edge-on early-type intruder forms the 1, while the collision-made blue ring forms the 0. The deck links a density wave of star formation to supernovae and a ring of X-ray binaries containing black holes.',
    mentorPriority: ['About 430–440 million light-years away in Cetus', 'Collision began about 40 million years ago', 'Blue eastern ring is the disrupted former spiral', 'Reddish off-center clump is its original nucleus', 'Nine luminous X-ray sources trace stellar-mass black holes'],
    sections: [
      { title: 'Why the system looks like 10', paragraphs: ['The western galaxy appears nearly edge-on and remains comparatively intact. It passed through the former spiral on the east, sending an expanding disturbance through that galaxy’s disk.', 'The eastern component now shows a clumpy blue ring of newly formed massive stars. Its reddish original nucleus sits off-center near the lower part of the ring.'], keyPoints: ['One = intruder galaxy', 'Zero = expanding star-forming ring', 'The nucleus and ring center do not coincide', 'The blue color comes from hot young stars'], examPrompt: 'Identify the intruder, the expanding ring, and the original nucleus in an unlabeled image.' },
      { title: 'From star formation to black holes', paragraphs: ['The collision triggered a strong wave of star formation. The most intense phase ended about 15 million years ago. Massive stars evolve quickly, explode as supernovae, and leave neutron stars or black holes.', 'Chandra detects nine exceptionally bright X-ray sources around the ring. Their luminosities and locations support the interpretation that they are stellar-mass black holes accreting from companion stars.'], keyPoints: ['X-ray sources appear after the massive-star population evolves', 'A compact remnant becomes bright when it accretes in a binary', 'The deck gives black-hole masses near 10–20 solar masses', 'A separate nuclear X-ray source may be a weakly fed supermassive black hole'], examPrompt: 'Construct the causal sequence from collision to blue ring to supernovae to luminous X-ray binaries.' },
      { title: 'Multiwavelength diagnosis', paragraphs: ['Hubble resolves optical structure, GALEX traces ultraviolet emission from young stars, Spitzer traces infrared-emitting dust, and Chandra locates high-energy compact sources.', 'The system extends about 115,000 light-years and is not assigned to a known galaxy group in the mentor material.'], keyPoints: ['Pink in the common composite represents Chandra X-rays', 'Optical and UV show the stellar ring', 'Infrared reveals dust and obscured activity'], examPrompt: 'Given the famous composite, explain why the pink points cannot be ordinary optical star clusters.' },
    ],
    sources: [{ label: 'NASA Chandra Arp 147', url: 'https://science.nasa.gov/missions/chandra/giant-ring-of-black-holes/' }],
  },
  {
    key: 'cartwheel',
    title: 'Cartwheel Galaxy',
    deck: 'Cartwheel Galaxy.pptx, slides 2–14',
    intro: 'The Cartwheel is the cleanest collision-generated ring example in the mentor set. Its inner ring, outer star-forming ring, and spokes record a nearly head-on passage through a former spiral galaxy.',
    mentorPriority: ['Rare ring galaxy in Sculptor', 'Roughly 500 million light-years away', 'Former spiral struck by a smaller intruder', 'Outer ring is an expanding star-forming wave', 'Spokes are disrupted or reforming spiral structure'],
    corrections: ['The mentor deck dates the collision to roughly 200–300 million years ago. NASA’s Webb article gives about 400 million years. Treat the event as a few hundred million years old and use the deck range when a question explicitly follows the slides.'],
    sections: [
      { title: 'Collision and expanding rings', paragraphs: ['A smaller galaxy passed through the disk near the center. The gravitational disturbance propagated outward like a ripple, compressing gas and dust as it moved.', 'The bright outer ring therefore marks current massive star formation. The compact inner ring surrounds the nucleus and contains hot dust and embedded star formation.'], keyPoints: ['The ring is a propagating density disturbance, not a rigid wheel', 'Gas compression explains the bright knots', 'Inner and outer rings host different conditions', 'The collision was nearly head-on'], examPrompt: 'Use a ripple model to explain why star formation concentrates in the outer ring.' },
      { title: 'Spokes and future evolution', paragraphs: ['Optical spokes connect the inner and outer rings. The mentor interprets them as shattered and reforming remnants of the original spiral arms. Optical and radio spokes do not perfectly overlap, showing that stars, gas, and magnetic structures trace different components.', 'As disturbed material falls back, the present wheel structure should fade. If further encounters do not interrupt it, spiral density patterns may eventually reform.'], keyPoints: ['Spokes preserve information about the old disk', 'Different wavelengths need not trace the same material', 'The current shape is temporary'], examPrompt: 'Why do the spokes support the claim that the Cartwheel was once a normal spiral?' },
      { title: 'Companions and high-energy sources', paragraphs: ['The Cartwheel dominates a small group with companions G1, G2, and G3. The deck identifies G3 as the likely intruder because a neutral-hydrogen tail links it to the Cartwheel.', 'The outer ring produced many massive stars, so it now contains many high-mass X-ray binaries and black-hole candidates. Supernova feedback creates holes, arcs, and hot bubbles in the ring.'], keyPoints: ['An H I tail is evidence about the intruder’s path', 'X-ray binaries are a delayed product of the starburst', 'JWST infrared data penetrates dust and separates young clusters'], examPrompt: 'State the evidence that favors G3 as the collision partner.' },
    ],
    sources: [{ label: 'NASA Webb Cartwheel', url: 'https://www.nasa.gov/universe/webb-captures-stellar-gymnastics-in-the-cartwheel-galaxy/' }],
  },
  {
    key: 'gw170817',
    title: 'GW170817',
    deck: 'GW170817.pptx, slides 3–12',
    intro: 'GW170817 is not a galaxy. It is a binary neutron-star merger located in the galaxy NGC 4993. The mentor deck focuses on the detection timeline, the kilonova, and why this event founded gravitational-wave multi-messenger astronomy.',
    mentorPriority: ['Detected 17 August 2017 by LIGO and Virgo', 'Host galaxy NGC 4993 in Hydra', 'About 100-second gravitational-wave chirp', 'GRB 170817A arrived about 1.7 seconds later', 'SSS17a = AT 2017gfo, the optical kilonova counterpart'],
    sections: [
      { title: 'The source: two neutron stars', paragraphs: ['A neutron star packs roughly a solar mass into a sphere about 10 kilometers in radius. In a binary, gravitational-wave emission removes orbital energy, so the stars spiral together and the wave frequency and amplitude rise into a chirp.', 'The deck gives a total system mass of about 2.73–3.09 solar masses. The long signal and inferred masses distinguished it from the earlier binary black-hole detections.'], keyPoints: ['Inspiral creates the rising chirp', 'Neutron stars contain nuclear-density matter', 'Component masses came from the waveform', 'The remnant’s final nature remains a separate question'], examPrompt: 'Explain how the gravitational-wave waveform identifies an inspiraling compact binary.' },
      { title: 'Detection timeline and localization', paragraphs: ['LIGO and Virgo detected the gravitational-wave signal at 12:41:04 UTC. Fermi and INTEGRAL detected the short gamma-ray burst GRB 170817A about 1.7 seconds later. Comparing arrival times at separated detectors narrowed the sky region.', 'About 11 hours after the merger, optical observers found SSS17a in NGC 4993. It later received the transient designation AT 2017gfo. Follow-up continued from gamma rays through radio wavelengths.'], keyPoints: ['Three gravitational-wave detectors improve localization', 'The gamma-ray burst supplied an independent trigger', 'The host identification provided redshift and environment', 'The optical source faded and reddened rapidly'], examPrompt: 'Put GW170817, GRB 170817A, and AT 2017gfo in chronological and physical order.' },
      { title: 'Kilonova and scientific significance', paragraphs: ['Neutron-rich ejecta expanded and cooled after the merger. Rapid neutron capture created heavy nuclei, and radioactive decay heated the ejecta to produce the kilonova light.', 'This was the first event observed in both gravitational waves and electromagnetic radiation. It connected at least some short gamma-ray bursts to neutron-star mergers, supported r-process production of heavy elements, and enabled a standard-siren estimate of cosmic expansion.'], keyPoints: ['Kilonova light comes from radioactive ejecta', 'R-process nucleosynthesis makes very heavy elements', 'Delayed X-ray and radio emission traces the outflow and jet interaction', 'A standard siren uses gravitational waves to estimate distance'], examPrompt: 'Why did the kilonova provide evidence about the origin of heavy elements?' },
    ],
    sources: [{ label: 'LIGO multi-messenger summary', url: 'https://ligo.org/science-summaries/GW170817MMA/' }],
  },
  {
    key: 'm51',
    title: 'Whirlpool Galaxy and NGC 5195',
    deck: 'M51.pptx, slides 2–18',
    intro: 'The M51 deck combines a textbook grand-design spiral with an interaction, an active nucleus, tidal debris, and wavelength-dependent structure. Learn M51a and M51b as a connected system.',
    mentorPriority: ['M51a = NGC 5194, the Whirlpool', 'M51b = NGC 5195, the smaller companion', 'Grand-design spiral in Canes Venatici', 'Companion interaction strengthens the arms', 'M51a contains an active Seyfert-like nucleus'],
    sections: [
      { title: 'Grand-design spiral structure', paragraphs: ['M51a has two continuous, high-contrast arms. In the mentor deck, those arms are active star-forming regions rather than fixed chains of the same stars. Gas enters the density pattern, compresses, forms stars, and then moves onward.', 'Visible light shows pink H II regions and blue young clusters. Near-infrared views suppress much of the starlight and expose the dust skeleton.'], keyPoints: ['Grand design means two prominent continuous arms', 'Dust lanes lie along compressed gas', 'Young blue stars and pink nebulae trace recent star formation', 'M51 is nearly face-on'], examPrompt: 'Describe the ordering of dust, ionized gas, and young stars across a spiral density wave.' },
      { title: 'Interaction with NGC 5195', paragraphs: ['NGC 5195 has passed close to or through M51a’s disk. The tidal encounter amplifies the spiral pattern and produces plumes and streams, including the Northwest Plume.', 'The apparent bridge near the end of an arm makes NGC 5195 an immediate identification clue. The companion is behind M51 in the common viewing geometry.'], keyPoints: ['The small yellow companion is M51b', 'Tidal effects extend much farther than the bright disks', 'M51 belongs to the M51 Group', 'Interaction can organize a grand-design pattern'], examPrompt: 'What evidence shows that M51 is interacting rather than merely aligned with a background galaxy?' },
      { title: 'Active nucleus and central dust', paragraphs: ['M51a contains a compact active nucleus powered by accretion onto a supermassive black hole. Hubble images show a dark X-shaped absorption feature across the core. The main bar of the X is interpreted as an edge-on dust ring that hides the nucleus.', 'Chandra reveals hot gas and high-energy activity around the center. The deck’s “miniature Seyfert” language refers to energetic nuclear emission, not the galaxy’s overall spiral morphology.'], keyPoints: ['AGN classification concerns the nucleus', 'Dust can hide the engine in visible light', 'X-rays penetrate or arise from high-energy central regions', 'Galaxy morphology and nuclear activity are separate labels'], examPrompt: 'Explain why a spiral galaxy can also be called a Seyfert galaxy.' },
    ],
    sources: [{ label: 'NASA Hubble Messier 51', url: 'https://science.nasa.gov/mission/hubble/science/explore-the-night-sky/hubble-messier-catalog/messier-51/' }],
  },
  {
    key: 'm82',
    title: 'M82, the Cigar Galaxy',
    deck: 'M82 - Cigar Galaxy.pptx, slides 2–21',
    intro: 'M82 is the mentor set’s richest starburst example. The deck connects tidal interaction with M81 to hidden spiral structure, a compact starburst core, a bipolar superwind, supernova SN 2014J, and ultraluminous X-ray sources.',
    mentorPriority: ['M82 = NGC 3034 in Ursa Major', 'Nearly edge-on and strongly dust obscured', 'M81 interaction increased star formation', 'Bipolar outflow is prominent above and below the disk', 'Know SN 2014J, M82 X-1, and M82 X-2'],
    sections: [
      { title: 'Hidden spiral and triggered starburst', paragraphs: ['M82 was long labeled irregular because its edge-on orientation, dust, and feedback hide its disk. Near-infrared observations revealed a central bar and two symmetric trailing spiral arms.', 'Tidal interaction with M81 began roughly 100 million years ago and funneled or compressed gas. The mentor deck states that the central region forms stars about ten times faster than the entire Milky Way.'], keyPoints: ['I0 describes its disturbed optical appearance', 'Near-IR reveals the barred spiral underneath', 'M81 is the external trigger', 'The starburst is concentrated in the inner few hundred parsecs'], examPrompt: 'Why did optical morphology lead to an irregular classification while infrared data revealed spiral arms?' },
      { title: 'Superwind and feedback', paragraphs: ['Massive stars, stellar winds, and frequent supernovae inject energy into the interstellar medium. The overpressured gas escapes perpendicular to the disk, producing the famous bipolar superwind.', 'Hydrogen emission appears in filaments above and below the galaxy. X-ray observations trace hotter gas, while infrared observations see warm dust and embedded star formation. Strong feedback will eventually remove or heat the fuel and reduce the burst.'], keyPoints: ['Outflow direction is roughly perpendicular to the disk', 'H-alpha and X-rays trace different gas temperatures', 'A starburst consumes and expels its own fuel', 'The narrow cigar body and broad plumes are distinct structures'], examPrompt: 'Connect the starburst to the shape and eventual self-limitation of the superwind.' },
      { title: 'SN 2014J and compact X-ray sources', paragraphs: ['SN 2014J was a nearby Type Ia supernova discovered in January 2014. Dust extinction complicates its use as a clean Type Ia template, but the same extinction probes M82’s interstellar material.', 'M82 X-1 is a leading intermediate-mass black-hole candidate. M82 X-2 is an ultraluminous X-ray pulsar in a binary. Its 1.37-second spin and super-Eddington apparent luminosity show that a neutron star, not only a black hole, can power a ULX.'], keyPoints: ['SN 2014J is Type Ia', 'X-1 is the black-hole candidate', 'X-2 is the neutron-star pulsar', 'Accretion geometry and magnetic channeling help explain super-Eddington emission'], examPrompt: 'Distinguish M82 X-1 from M82 X-2 and explain why X-2 changed the interpretation of ULXs.' },
    ],
    sources: [{ label: 'NASA Hubble Messier 82', url: 'https://science.nasa.gov/mission/hubble/science/explore-the-night-sky/hubble-messier-catalog/messier-82/' }],
  },
  {
    key: 'mcg-07-33-027',
    title: 'MCG+07-33-027',
    deck: 'MCG+07-33-027.pptx, slides 2–8',
    intro: 'This object tests whether you understand that starbursts do not always require an obvious interaction. Its clean face-on spiral arms contrast with its puzzling isolation.',
    mentorPriority: ['Face-on Sa spiral in Hercules', 'About 329 million light-years away', 'Two clear primary arms', 'Bright gas-rich star-forming regions', 'Isolated field galaxy with an unexplained starburst'],
    sections: [
      { title: 'Recognition and classification', paragraphs: ['The face-on orientation makes the disk and two main arms easy to trace. Bright blue clusters and pink or clumpy gas regions mark intense recent star formation.', 'The Sa label points to relatively tightly wound arms and a substantial central concentration. A bright point beside the galaxy in the Hubble image is a foreground Milky Way star, not a companion.'], keyPoints: ['Face-on two-arm pattern', 'Do not misidentify the foreground star as an interacting galaxy', 'Sa is a morphological label', 'Starburst describes activity, not shape'], examPrompt: 'Use the image to separate morphology, viewing angle, and star-formation state.' },
      { title: 'The isolated-starburst puzzle', paragraphs: ['Many starbursts follow mergers or close tidal encounters because those processes compress gas. MCG+07-33-027 is a field galaxy without an obvious nearby perturber.', 'The key scientific question is therefore the trigger. Internal disk instability, bar-driven gas motion, or a past event might contribute, but the mentor deck treats the cause as unknown.'], keyPoints: ['Isolation is the defining contrast', 'A gas reservoir is necessary but does not identify the trigger', 'Do not invent a collision partner', 'SN 2005bk occurred in this galaxy'], examPrompt: 'Why is MCG+07-33-027 evidence that a starburst classification does not prove a recent collision?' },
      { title: 'Reading the catalog name', paragraphs: ['MCG refers to the Morphological Catalogue of Galaxies. The remaining numbers encode the declination zone, catalog field, and running object number.', 'The designation is a location-based catalog label, not a physical classification.'], keyPoints: ['Catalog names and morphology codes serve different purposes', '+07 identifies a declination zone', '027 is the running object number in the field'], examPrompt: 'Explain what information the MCG designation carries and what it does not tell you.' },
    ],
    sources: [{ label: 'NASA Hubble secluded starburst', url: 'https://science.nasa.gov/missions/hubble/hubble-spots-a-secluded-starburst-galaxy/' }],
  },
  {
    key: 'ngc-1569',
    title: 'NGC 1569',
    deck: 'NGC 1569.pptx, slides 2–8',
    intro: 'NGC 1569 is a nearby dwarf irregular starburst whose small size makes its enormous star-formation intensity especially striking. It links super star clusters to superbubbles, enriched outflows, and environmental triggering.',
    mentorPriority: ['IBm dwarf irregular in Camelopardalis', 'About 11 million light-years away', 'Three major super star clusters: A1, A2, and B', 'Star formation per unit size is extreme', 'Filaments and bubbles come from winds and supernovae'],
    sections: [
      { title: 'Dwarf irregular morphology', paragraphs: ['NGC 1569 lacks a symmetric disk, regular arms, and a dominant classical bulge. Its IBm code indicates an irregular Magellanic form with a bar-like component.', 'Because it is close, Hubble resolves individual stars and clusters. The system is smaller than the Small Magellanic Cloud yet optically bright for its size.'], keyPoints: ['Irregular does not mean physically unstructured', 'Dwarf refers to scale or luminosity', 'Resolved stars allow a direct star-formation history', 'A1 and A2 can blur into one source at low resolution'], examPrompt: 'Decode IBm and explain why angular resolution changes the apparent number of central clusters.' },
      { title: 'Super star clusters and starburst intensity', paragraphs: ['The mentor deck identifies A1, A2, and B as exceptionally massive compact young clusters. It quotes an absolute star-formation rate around 0.2 to 0.5 solar masses per year, modest compared with a giant galaxy but extraordinary for such a small system.', 'This distinction between total rate and rate per unit area or mass is a common test concept. A dwarf can qualify as a strong starburst without forming more stars in total than the Milky Way.'], keyPoints: ['Use specific rate or surface density when comparing unequal galaxies', 'Each super star cluster contains an enormous young population', 'The recent burst lasted tens of millions of years'], examPrompt: 'Why can 0.3 solar masses per year represent a more extreme starburst than a larger numerical rate in a massive spiral?' },
      { title: 'Feedback and environment', paragraphs: ['Stellar winds and supernovae inflate ionized shells and million-degree X-ray bubbles. In a low-mass dwarf, the shallow gravitational potential makes it easier for a wind to remove gas and metals.', 'The deck links the burst to interactions within the IC 342/Maffei Group, especially a nearby neutral-hydrogen cloud.'], keyPoints: ['Optical hydrogen filaments trace warm ionized gas', 'X-rays trace much hotter gas', 'Outflows can regulate future star formation', 'Environmental gas can trigger a burst without a spectacular optical merger'], examPrompt: 'Predict how the same feedback energy affects a dwarf galaxy differently from a giant spiral.' },
    ],
    sources: [{ label: 'NASA Hubble NGC 1569', url: 'https://science.nasa.gov/asset/hubble/starburst-galaxy-ngc-1569/' }],
  },
  {
    key: 'ngc-4536',
    title: 'NGC 4536',
    deck: 'NGC 4536.pptx, slides 2–13',
    intro: 'NGC 4536 is the mentor example of an intermediate spiral with a weak bar, an inner ring-like structure, and vigorous star formation around the nucleus and arms.',
    mentorPriority: ['SAB(rs)bc in Virgo', 'About 49 million light-years away', 'Weak bar and partial inner ring', 'No classical bulge', 'Member of the M61 Group within the Virgo II Groups'],
    sections: [
      { title: 'Decoding SAB(rs)bc', paragraphs: ['SAB means the bar strength falls between unbarred SA and strongly barred SB. The (rs) notation describes a transition between a closed inner ring and spiral structure. The bc stage indicates moderately loose, well-defined arms and a relatively modest central concentration.', 'The mentor explicitly notes the absence of a classical bulge. Do not assume every bright spiral center contains one.'], keyPoints: ['SAB = weak or intermediate bar', '(rs) = inner ring/spiral transition', 'bc = intermediate arm winding', 'Morphology encodes several independent visible features'], examPrompt: 'Decode every part of SAB(rs)bc without treating it as one memorized word.' },
      { title: 'Starburst geography', paragraphs: ['NGC 4536 has optical characteristics associated with strong H II emission. Star formation appears in the ring surrounding the bar and nucleus and along the spiral arms.', 'Bars can torque gas and move it inward. Accumulation near resonances can form a ring where gas becomes dense enough for rapid star formation.'], keyPoints: ['H II emission requires ionizing massive stars', 'The bar can rearrange gas', 'A ring can be a star-forming structure rather than a collision ring', 'SN 1981B occurred here'], examPrompt: 'Contrast NGC 4536’s inner star-forming ring with the collision-generated outer ring of the Cartwheel.' },
      { title: 'Wavelength and environment', paragraphs: ['Ultraviolet emphasizes hot young stars, infrared emphasizes dust heated by star formation, and visible images show the arms and dust lanes together.', 'The galaxy belongs to the M61 Group, itself within the Virgo II grouping. That is distinct from membership in the dense central Virgo Cluster.'], keyPoints: ['Do not equate Virgo constellation with Virgo Cluster membership', 'Group hierarchy can appear in association questions', 'Multi-band agreement strengthens the starburst interpretation'], examPrompt: 'Explain why location in the constellation Virgo does not by itself determine cluster membership.' },
    ],
    sources: [{ label: 'NASA Hubble NGC 4536', url: 'https://science.nasa.gov/missions/hubble/hubble-sees-starbursts-in-virgo/' }],
  },
  {
    key: 'sombrero',
    title: 'Sombrero Galaxy',
    deck: 'Sombrero Galaxy.pptx, slides 2–17',
    intro: 'Sombrero combines a nearly edge-on disk and sharp dust ring with an enormous bulge and halo. Its structure makes a simple spiral-versus-elliptical label inadequate and creates several likely comparison questions.',
    mentorPriority: ['M104 = NGC 4594 in Virgo', 'Nearly edge-on disk with a sharp dust lane', 'Very large bulge and metal-rich halo', 'Roughly 2,000 globular clusters', 'LINER nucleus with an approximately billion-solar-mass black hole'],
    corrections: ['The deck’s data table prints 2.50 million light-years, which is Andromeda’s distance and conflicts with the rest of the deck. NASA gives about 28 million light-years. Study approximately 28–30 million light-years for M104.'],
    sections: [
      { title: 'The hat-shaped anatomy', paragraphs: ['We view M104 only a few degrees above its equatorial plane. Dust in the thin disk therefore forms a dark band across the much rounder, brighter bulge.', 'The dust lane is a roughly symmetric ring containing much of the cold atomic and molecular gas. Infrared spectroscopy shows that this ring is the main site of current star formation.'], keyPoints: ['Dark band = dust in the disk', 'White dome = central bulge and halo stars', 'The dust ring is also a star-forming reservoir', 'Inclination produces the signature silhouette'], examPrompt: 'Explain how viewing angle turns a circular dust ring into the dark horizontal lane in images.' },
      { title: 'Spiral or elliptical?', paragraphs: ['The disk and dust ring support a spiral classification, commonly SA(s)a. The enormous smooth halo, massive bulge, and rich globular-cluster system resemble an elliptical galaxy.', 'The deck emphasizes that Hubble and Spitzer observations made the halo appear larger and more massive than early estimates. This is why the Sombrero is a useful warning against classifying a galaxy from one feature alone.'], keyPoints: ['Disk features point toward spiral', 'Halo and bulge point toward giant elliptical-like structure', 'M104 is often treated as a peculiar or mixed case', 'Morphology depends on which component and wavelength dominate'], examPrompt: 'Give evidence on both sides of the Sombrero spiral-versus-elliptical classification debate.' },
      { title: 'Halo, clusters, and nucleus', paragraphs: ['M104 contains roughly 1,200 to 2,000 globular clusters, about ten times the Milky Way count often quoted in outreach material. Its halo contains unexpectedly metal-rich stars and relatively few of the old metal-poor field stars expected in a conventional massive halo.', 'The nucleus is a LINER, and X-ray evidence indicates accretion around a black hole near one billion solar masses. The deck also places M104 as an isolated giant anchoring the Virgo II Groups rather than a member of the central Virgo Cluster.'], keyPoints: ['LINER is a nuclear spectral classification', 'Globular clusters are a major recognition and fact clue', 'Metallicity records enrichment and merger history', 'Virgo constellation, Virgo Cluster, and Virgo II Groups are different ideas'], examPrompt: 'How could a past merger help explain M104’s massive halo without an obviously disturbed present-day disk?' },
    ],
    sources: [{ label: 'NASA Hubble Messier 104', url: 'https://science.nasa.gov/mission/hubble/science/explore-the-night-sky/hubble-messier-catalog/messier-104/' }],
  },
  {
    key: 'terzan-5',
    title: 'Terzan 5',
    deck: 'Terzan 5.pptx, slides 2–13',
    intro: 'Terzan 5 is not a galaxy and, according to the mentor’s newest material, not a true globular cluster. It is the prototype bulge fossil fragment: a dense surviving system with multiple generations of stars that records the Milky Way bulge’s assembly.',
    mentorPriority: ['Located in the Milky Way bulge in Sagittarius', 'Looks like a globular cluster but has multiple ages and iron abundances', 'Four stellar generations in the 2026 Webb/Hubble result', 'Contains an exceptional millisecond-pulsar population', 'Fastest known pulsar PSR J1748−2446ad spins at 716 Hz'],
    corrections: ['The deck’s Type row says “SA(s)a or E,” a galaxy classification copied from another object. The deck’s own slides 3, 5, and 6 correctly classify Terzan 5 as a bulge fossil fragment rather than a galaxy or normal globular cluster.'],
    sections: [
      { title: 'Why it is not a normal globular cluster', paragraphs: ['A standard globular cluster forms most of its stars in one early episode, so its stars share nearly the same age and initial composition. Terzan 5 instead contains populations with different ages, iron abundances, and alpha-element patterns.', 'The newest mentor material lists four formation episodes at roughly 12.5, 4.7, 3.8, and 2.5 billion years ago. Retaining gas and supernova products across multiple episodes required a deeper gravitational potential than a typical globular cluster.'], keyPoints: ['Multiple turnoffs in a color-magnitude diagram imply multiple ages', 'Different iron abundances require self-enrichment', 'Dust reddening makes infrared observations essential', 'A multi-population system can masquerade as a cluster'], examPrompt: 'Use age and abundance evidence to reject the ordinary-globular-cluster hypothesis.' },
      { title: 'Bulge fossil fragment', paragraphs: ['The working model identifies Terzan 5 as the remnant of a much larger primordial clump that participated in building the Milky Way bulge. It formed independently, survived later mergers, and never completely mixed into the surrounding bulge.', 'Liller 1 is the other confirmed example named in the current Webb release. These objects give astronomers a surviving local record of the clumpy early stages of bulge formation.'], keyPoints: ['BFF means bulge fossil fragment', 'The oldest population formed about 12.5 billion years ago', 'The system resembles an early bulge building block', 'Its stellar chemistry links it to the Galactic bulge'], examPrompt: 'Distinguish a bulge fossil fragment from both a globular cluster and a dwarf galaxy.' },
      { title: 'Pulsars, binaries, and high-energy emission', paragraphs: ['The dense core drives frequent close stellar encounters. These encounters form compact binaries and can recycle neutron stars into millisecond pulsars by transferring angular momentum through accretion.', 'The deck lists 49 known millisecond radio pulsars as of December 2023 and suggests the true population may be much larger. Terzan 5 also contains X-ray binaries, cataclysmic variables, diffuse nonthermal X-rays, and gamma-ray emission.'], keyPoints: ['High stellar density raises the encounter rate', 'Accretion spins old neutron stars up into millisecond pulsars', 'PSR J1748−2446ad has a 1.40 ms period', 'Inverse Compton scattering can contribute to very-high-energy gamma rays'], examPrompt: 'Explain the causal link between core density, binary formation, and the millisecond-pulsar population.' },
    ],
    sources: [{ label: 'ESA Webb Terzan 5 release', url: 'https://esawebb.org/news/weic2611/' }],
  },
];

export const galaxyTypeArticles: StudyArticle[] = [
  { key: 'spiral', title: 'Spiral galaxies', deck: 'Repeated foundation slides in the mentor DSO decks', intro: 'Spirals combine a thin rotating disk, spiral density patterns, a central bulge, and a much larger halo. The classification describes visible structure, not a fixed evolutionary age.', mentorPriority: ['Disk, bulge, arms, halo, and central black hole', 'Young stars favor gas-rich arms', 'Old stars dominate the bulge and halo', 'Sa to Sd tracks arm winding and bulge prominence'], sections: [{ title: 'Structure and stellar populations', paragraphs: ['The disk contains most of the cold gas, dust, and active star formation. The bulge is thicker and contains older stars on less disk-like orbits. A faint halo holds old stars, globular clusters, and a dominant dark-matter component.', 'Spiral arms are density patterns. Gas entering a pattern compresses and forms stars, so the arms stay visible even though individual stars move through them.'], keyPoints: ['Tight arms and large bulge favor Sa', 'Loose fragmented arms and small bulge favor Sc or Sd', 'Face-on views reveal arms; edge-on views reveal disk thickness and dust'], examPrompt: 'Classify an Sa versus an Sc from bulge size, arm winding, and clumpiness.' }], sources: [{ label: 'NASA galaxy types', url: 'https://science.nasa.gov/universe/galaxies/types/' }] },
  { key: 'barred-spiral', title: 'Barred spiral galaxies', deck: 'Andromeda, Antennae, and NGC 4536 mentor decks', intro: 'A bar is an elongated stellar structure through the central region. It changes stellar and gas orbits and often channels gas toward rings or the nucleus.', mentorPriority: ['SB marks a strong bar; SAB marks an intermediate bar', 'Arms usually begin near the bar ends', 'About two-thirds of nearby spirals are barred', 'The Milky Way and Andromeda are barred'], sections: [{ title: 'Gas flow and recognition', paragraphs: ['A bar is not a solid rotating rod. It is an organized orbital pattern. Gravitational torques from the pattern move angular momentum and can direct gas inward.', 'On images, look for a straight central light distribution with arms emerging from its ends. Dust and inclination can conceal the bar, so near-infrared observations often reveal it more clearly.'], keyPoints: ['Near-IR penetrates dust and emphasizes old bar stars', 'Bars can feed circumnuclear rings and starbursts', 'SAB is not the same as SB'], examPrompt: 'Explain why NGC 4536’s weak bar is physically related to its central star-forming ring.' }], sources: [{ label: 'NASA Hubble tuning fork', url: 'https://science.nasa.gov/asset/hubble/the-hubble-tuning-fork-classification-of-galaxies/' }] },
  { key: 'elliptical', title: 'Elliptical galaxies', deck: 'Arp 147, M51, and Sombrero mentor decks', intro: 'Ellipticals appear smooth and range from nearly round E0 to elongated E7. They usually contain older stars, little cold gas, and weak current star formation.', mentorPriority: ['E0–E7 describes apparent ellipticity', 'Stellar orbits are not confined to a thin rotating disk', 'Old populations and many globular clusters are common', 'Major mergers can create elliptical remnants'], sections: [{ title: 'Shape, content, and formation', paragraphs: ['Elliptical galaxies lack the dust lanes and blue arm structure of spirals. Their stars move on a broad distribution of orbits, creating a three-dimensional spheroid.', 'The lack of cold molecular gas limits new star formation. Mergers can briefly supply gas and trigger star formation before the remnant settles into a smoother system.'], keyPoints: ['E7 is more elongated than E0', 'The sequence does not measure age', 'A smooth red appearance is evidence, not an absolute rule'], examPrompt: 'Why does the Antennae’s predicted future elliptical remnant still undergo intense star formation today?' }], sources: [{ label: 'NASA galaxy types', url: 'https://science.nasa.gov/universe/galaxies/types/' }] },
  { key: 'lenticular', title: 'Lenticular galaxies', deck: 'Arp 143 and M51 mentor decks', intro: 'Lenticulars, labeled S0, have a disk and bulge but no prominent spiral arms. Their structure resembles a spiral whose gas and arms have faded, while their stellar population resembles an elliptical.', mentorPriority: ['S0 sits at the fork between ellipticals and spirals', 'Disk present, large-scale arms absent', 'Little gas and little ongoing star formation', 'NGC 2444 and possibly NGC 5195 are relevant examples'], sections: [{ title: 'A disk without active arms', paragraphs: ['The key is to separate geometry from star formation. A lenticular can have a clear flattened disk while lacking the gas-rich arm pattern of a spiral.', 'Possible formation paths include gas stripping, exhausted star formation, and mergers. The tuning fork position does not prove one universal evolutionary path.'], keyPoints: ['Edge-on S0 galaxies can resemble ellipticals', 'Dust may still be present', 'Old stars do not erase the disk'], examPrompt: 'What observation would distinguish an edge-on lenticular from a true elliptical?' }], sources: [{ label: 'NASA lenticular example', url: 'https://science.nasa.gov/missions/hubble/a-galaxy-at-the-center-of-the-hubble-tuning-fork/' }] },
  { key: 'irregular-dwarf', title: 'Irregular and dwarf irregular galaxies', deck: 'M82 and NGC 1569 mentor decks', intro: 'Irregular galaxies do not fit the regular Hubble sequence. Some retain bars or partial structure, while others are strongly distorted by interactions. Dwarf irregulars are small, gas-rich, and often metal-poor.', mentorPriority: ['Irr I has some structure; Irr II is more chaotic', 'Sm retains spiral structure; Im does not', 'dIrr systems have low luminosity and often low metallicity', 'NGC 1569 is IBm; M82 only appears strongly irregular in optical light'], sections: [{ title: 'Classification without assuming cause', paragraphs: ['Irregular appearance can arise from low mass, patchy star formation, tidal disturbance, or obscuration. The label describes appearance and does not by itself identify which cause applies.', 'Dwarfs lose gas more easily because their escape speeds are low. This makes stellar feedback central to their evolution and metal enrichment.'], keyPoints: ['Irregular is not synonymous with interacting', 'A dwarf can have an intense specific star-formation rate', 'Infrared imaging may reveal hidden regular structure'], examPrompt: 'Contrast the reasons NGC 1569 and M82 appear irregular.' }], sources: [{ label: 'NASA galaxy types', url: 'https://science.nasa.gov/universe/galaxies/types/' }] },
  { key: 'interacting', title: 'Interacting and merging galaxies', deck: 'Antennae, Arp 143, Arp 147, Cartwheel, and M51 mentor decks', intro: 'Galaxy interactions range from flybys to minor and major mergers. Gravity distorts stellar orbits, while colliding gas clouds compress and often ignite star formation.', mentorPriority: ['Tidal tails and bridges diagnose interaction', 'Stars rarely collide directly', 'Gas responds dissipatively and can form stars', 'Major mergers combine similar-sized galaxies'], sections: [{ title: 'Reading the evidence', paragraphs: ['Tails form when tidal forces pull stars and gas outward. Bridges link the participants. Rings can form after a near head-on passage, while off-center passages often produce asymmetric arms and plumes.', 'Interactions can also drive gas inward, feeding central starbursts or an active nucleus. The outcome depends on mass ratio, geometry, gas content, and orbital energy.'], keyPoints: ['A flyby need not end in merger', 'Minor merger = unequal masses', 'Major merger = comparable masses', 'Morphological scars can outlive the closest passage'], examPrompt: 'Infer collision geometry from a tidal-tail system versus a symmetric expanding ring.' }], sources: [{ label: 'NASA Hubble galaxies', url: 'https://science.nasa.gov/mission/hubble/science/universe-uncovered/hubble-galaxies/' }] },
  { key: 'ring', title: 'Ring galaxies', deck: 'Arp 143, Arp 147, and Cartwheel mentor decks', intro: 'A collisional ring forms when a smaller galaxy passes through a disk and launches an expanding density wave. The ring glows because compressed gas forms short-lived massive stars.', mentorPriority: ['Bright blue ring = young massive stars', 'Original nucleus may sit off-center', 'Intruder may remain nearby', 'Arp 147 and Cartwheel are the clearest examples'], sections: [{ title: 'A wave rather than a material hoop', paragraphs: ['The outward-moving disturbance organizes where star formation occurs. Individual gas clouds and stars do not all travel outward at the same speed as one solid ring.', 'An off-center impact makes an asymmetric ring. A later encounter can distort a ring into a triangle, as in Arp 143.'], keyPoints: ['Look for age gradients across the ring', 'Compact X-ray binaries appear after massive stars die', 'Accretion can also make rings, so collision evidence matters'], examPrompt: 'What observation would support a collisional origin rather than a resonance or accretion ring?' }], sources: [{ label: 'NASA Cartwheel', url: 'https://www.nasa.gov/universe/webb-captures-stellar-gymnastics-in-the-cartwheel-galaxy/' }] },
  { key: 'starburst', title: 'Starburst galaxies', deck: 'M82, NGC 1569, NGC 4536, and MCG+07-33-027 mentor decks', intro: 'A starburst is a temporary physical state in which a galaxy forms stars fast enough to consume or disrupt its gas reservoir on a short timescale. It is not a Hubble morphology.', mentorPriority: ['Requires abundant cold gas plus a trigger', 'Mergers are common triggers but not required', 'Massive stars lead quickly to supernovae and winds', 'Feedback can quench the same burst'], sections: [{ title: 'Rates, triggers, and feedback', paragraphs: ['Compare star-formation rate with galaxy mass or area. NGC 1569’s total rate is smaller than a giant spiral’s, yet its rate per unit size is extreme.', 'Tidal compression triggers M82 and the Antennae. A weak bar may organize gas in NGC 4536. MCG+07-33-027 shows that an isolated galaxy can have a starburst whose trigger remains uncertain.'], keyPoints: ['H-alpha, UV, and infrared diagnose different parts of star formation', 'X-rays trace compact remnants and hot wind fluid', 'A starburst cannot continue indefinitely'], examPrompt: 'Choose the best star-formation tracer for unobscured young stars, ionized gas, and dust-hidden regions.' }], sources: [{ label: 'NASA galaxy glossary', url: 'https://science.nasa.gov/universe/glossary/' }] },
  { key: 'active-peculiar', title: 'Active, peculiar, and amorphous galaxies', deck: 'M51, Sombrero, and interaction mentor decks', intro: 'These labels answer different questions. AGN and LINER describe nuclear emission, while peculiar and amorphous describe unusual large-scale appearance.', mentorPriority: ['AGN energy comes from accretion onto a supermassive black hole', 'Seyfert and LINER are nuclear spectral classes', 'Pec marks morphology outside a normal sequence', 'A galaxy can carry both morphology and activity labels'], sections: [{ title: 'Keeping classifications separate', paragraphs: ['M51 is a spiral with a Seyfert-like active nucleus. Sombrero has a LINER nucleus. Their activity labels do not replace their structural classifications.', 'A peculiar or amorphous appearance can record tidal disturbance, merger history, or heavy dust. It does not automatically mean the nucleus is active.'], keyPoints: ['Accretion disks convert gravitational energy into radiation', 'Orientation and obscuration change how an AGN appears', 'Do not infer AGN solely from distorted shape'], examPrompt: 'Explain how one galaxy can simultaneously be SAB(rs)bc, starburst, and active.' }], sources: [{ label: 'NASA active galaxy types', url: 'https://science.nasa.gov/universe/galaxies/types/' }] },
];
